ind_dealer/Dcenters/urls.py
from django.urls import path, include
from . import views
from rest_framework.urlpatterns import format_suffix_patterns


urlpatterns = [
    path('dc/', views.DealerCenterList.as_view(), name='dc'),
    path('dc/<int:pk>/', views.DealerCenterDetail.as_view()),
    path('veh/', views.VehicleList.as_view(), name='veh'),
    path('veh/<int:pk>/', views.VehicleDetail.as_view()),
    path('', views.DealerCenterFront.as_view(), name='home'),
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
]

ind_dealer/ind_dealer/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Dcenters.urls')),
    path('auth/', include('rest_framework.urls')),
]

ind_dealer/Dcenters/models.py
from django.db import models
import datetime



class DealerCenter(models.Model):
    dealer = models.ForeignKey('auth.User', on_delete=models.CASCADE, verbose_name='Дилер')
    center_name = models.CharField(max_length=100, unique=True, verbose_name='Название центра')
    selling = models.BooleanField(default=False, verbose_name='Продажа ТС')
    repair = models.BooleanField(default=False, verbose_name='Ремонт ТС')
    parts_stor = models.BooleanField(default=False, verbose_name='Склад ЗЧ')
    vehicle_stor = models.BooleanField(default=False, verbose_name='Склад ТС')

    def __str__(self):
        return f'{self.dealer} - {self.center_name}'

    class Meta:
        db_table = 'dealer_centers'


class Vehicle(models.Model):
    vin = models.CharField(max_length=5, unique=True, verbose_name='#VIN')
    brand = models.CharField(max_length=50, verbose_name='Бренд')
    m_type = models.CharField(max_length=50, verbose_name='Модель')
    color = models.CharField(max_length=50, verbose_name='Цвет')
    date_arr = models.DateField(verbose_name='Дата поступления к дилеру (ГГГГ-ММ-ДД)')
    date_dc = models.DateField(verbose_name='Дата поступления в дилерский центр (ГГГГ-ММ-ДД)')
    dealer_center = models.ForeignKey(DealerCenter, on_delete=models.CASCADE, verbose_name='Дилерский центр')
    dealer = models.ForeignKey('auth.User', on_delete=models.CASCADE, verbose_name='Дилер')

    def __str__(self):
        return f'{self.vin} - {self.brand} {self.m_type}'

    class Meta:
        db_table = 'vehicles'
        ordering = ['id']

ind_dealer/Dcenters/forms.py
from django.forms import ModelForm
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from .models import DealerCenter, Vehicle
from rest_framework import serializers



class DealerCenterForm(ModelForm):

    class Meta:
        model = DealerCenter
        exclude = ['dealer']


class VehicleForm(ModelForm):

    class Meta:
        model = Vehicle
        exclude = ['dealer']

class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

ind_dealer/Dcenters/views.py
from .models import DealerCenter, Vehicle
from .serializers import DealerCenterSerializer, VehicleSerializer
from .forms import DealerCenterForm, VehicleForm, LoginUserForm
from .permissions import IsOwner

from django.views import View
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import logout

from rest_framework import permissions, renderers, generics
from rest_framework.response import Response
from rest_framework.reverse import reverse
from rest_framework import permissions



class DealerCenterList(generics.ListCreateAPIView):
    queryset = DealerCenter.objects.all()
    serializer_class = DealerCenterSerializer
    permission_classes = [permissions.IsAuthenticated, IsOwner]

    def get_queryset(self):
        d = self.request.user
        return DealerCenter.objects.filter(dealer=d)

class DealerCenterDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = DealerCenter.objects.all()
    serializer_class = DealerCenterSerializer
    permission_classes = [IsOwner]


class VehicleList(generics.ListCreateAPIView):
    queryset = Vehicle.objects.all()
    serializer_class = VehicleSerializer
    permission_classes = [permissions.IsAuthenticated, IsOwner]

    def get_queryset(self):
        d = self.request.user
        return Vehicle.objects.filter(dealer=d)

class VehicleDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Vehicle.objects.all()
    serializer_class = VehicleSerializer
    permission_classes = [IsOwner]


class DealerCenterFront(View):

    def get(self, request, *args, **kwargs):
        all_user = User.objects.all()
        try:
            all_dc = DealerCenter.objects.filter(dealer=request.user)
        except:
            all_dc = []
        all_veh = Vehicle.objects.all()
        new_dc = DealerCenterForm
        new_veh = VehicleForm
        cur_dealer = request.user

        return render(request, 'Dcenters/dcveh.html', context={
        'getdc': all_dc,
        'getveh': all_veh,
        'postdc': new_dc,
        'postveh': new_veh,
        'd': cur_dealer,
        'all_d': all_user
        })

    #def post(self, request):
    #    if request.method == "POST":
    #        form = DealerCenterForm(request.POST)
    #        post = form.save()
    #        post.save()
    #        return redirect('home')
    #    else:
    #        form = DealerCenterForm()
    #    return render(request, 'Dcenters/dcveh.html', {'postdc': form})


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'Dcenters/login.html'

    def get_success_url(self):
        return reverse('home')


def logout_user(request):
    logout(request)
    return redirect('home')

ind_dealer/Dcenters/templates/Dcenters/dcveh.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
</head>
<body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
{% if d in all_d %}
<div class="w-50 p-2">
    <h2 class="p-3 mb-2 bg-warning text-dark text-center">Дилер: <b>{{ d }}</b></h2>
    <h5 class="p-3 mb-2 bg-danger-subtle text-emphasis-danger text-center"><a href="{% url 'logout' %}">Выйти из ситемы</a></h5>
 <h3 class="text-warning bg-dark text-center">Дилерские центры и информация:</h3>
 {% for i in getdc %}
    <p class="text-info bg-dark">Дилерский центр - <b>{{i.center_name}}</b></p>
    <div class="p-3 mb-2 bg-info-subtle text-emphasis-info">
        <b>Возможности центра:</b><br>
    {% if i.selling == True %}- Продажа ТС<br>{% endif %}
    {% if i.repair == True %}- Ремонт ТС<br>{% endif %}
    {% if i.parts_stor == True %}- Склад ЗЧ<br>{% endif %}
    {% if i.vehicle_stor == True %}- Склад ТС<br>{% endif %}
    </div>
    <div class="p-3 mb-2 bg-info-subtle text-emphasis-info">
        <b>Список закреплённых машин:</b><br>
    {% for v in i.vehicle_set.all %}
       {{v.vin}} - {{v.brand}} {{v.m_type}}, color: {{v.color}}, даты появления: {{v.date_arr}} - {{v.date_dc}}<br>
    {% endfor %}
    </div>
 {% endfor %}

 <h3 class="text-warning bg-dark text-center">Добавить новый дилерский центр:</h3>
 <div class="p-3 mb-2 bg-dark-subtle text-emphasis-dark">
     <form action="{% url 'dc' %}" method="post">
     {% csrf_token %}
     <table>{{ postdc.as_table }}</table>
     <input type="submit" class="btn btn-outline-primary --bs-dark" value="Добавить">
     </form>
 </div>

 <h3 class="text-warning bg-dark text-center">Добавить новое транспортное средство:</h3>
 <div class="p-3 mb-2 bg-dark-subtle text-emphasis-dark">
     <form action="{% url 'veh' %}" method="post">
     {% csrf_token %}
     <table>{{ postveh.as_table }}</table>
     <input type="submit" class="btn btn-outline-primary" value="Добавить">
     </form>
</div>
{% else %}
<div class="w-50 p-2">
    <h3 class="p-3 mb-2 bg-warning text-dark text-center">Пожалуйста, <a href="{% url 'login' %}">войдите</a> в систему</h3>
</div>
{% endif %}

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js" integrity="sha384-Rx+T1VzGupg4BHQYs2gCW9It+akI2MM/mndMCy36UVfodzcJcF0GGLxZIzObiEfa" crossorigin="anonymous"></script>
</body>
</html>

ind_dealer/Dcenters/templates/Dcenters/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
</head>
<body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
<h1>{{ title }}</h1>
<div class="position-absolute top-50 start-50 translate-middle p-3 mb-2 bg-info-subtle text-emphasis-info border border-primary border-2">
<form method="post">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <button type="submit" class="btn btn-outline-primary">Войти</button>
</form>
</div>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js" integrity="sha384-Rx+T1VzGupg4BHQYs2gCW9It+akI2MM/mndMCy36UVfodzcJcF0GGLxZIzObiEfa" crossorigin="anonymous"></script>
</body>
</html>